version: '2'

services:
  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_PASSWORD: 
      WORDPRESS_DB_NAME: blog
    volumes:
     - ./wordpress1:/var/www/html

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: blog
    volumes:
      - ./wordpress1/blog.sql:/docker-entrypoint-initdb.d/blog.sql